### ISSUE TITLE
[dialog/modal] Transclude issue with bootstrap 0.2

### ISSUE THREAD

**Issue by ffesseler** [angular-ui/bootstrap#201]
I've made a custom directive on top of ui bootstrap modal directive so I can use the same modal template everywhere in my app. 

Please see this example : 

http://plnkr.co/edit/2K0SRC?p=preview

It works well with bootstrap 0.1. However if I use bootstrap 0.2 instead, I get this error

```
TypeError: undefined is not a function
```
