### ISSUE TITLE
ngModelCtrl.$render() is  not defined after update from 0.10 to 0.11

### ISSUE THREAD

**Issue by daniel79** [angular-ui/bootstrap#2157]
TypeError: undefined is not a function
    at Object.fn (http://0.0.0.0:9000/bower_components/angular-bootstrap/ui-bootstrap-tpls.js:2207:19)
    at Scope.$digest (http://0.0.0.0:9000/bower_components/angular/angular.js:12251:29)
    at Scope.$apply (http://0.0.0.0:9000/bower_components/angular/angular.js:12516:24)
    at done (http://0.0.0.0:9000/bower_components/angular/angular.js:8204:45)
    at completeRequest (http://0.0.0.0:9000/bower_components/angular/angular.js:8412:7)
    at XMLHttpRequest.xhr.onreadystatechange (http://0.0.0.0:9000/bower_components/angular/angular.js:8351:11)

**Comment by deepsaurabh** [comment]
Hi,
I faced the same issue in pagination and it is because ng-model was introduced in ui-bootstrap-tpls-0.11.0.js 
Explanation and solution for the same is explained here - (https://stackoverflow.com/questions/23419059/pagination-in-angular-ui-bootstrap-throwing-error-compilenonassign/23419555#23419555)
