### ISSUE TITLE
Opening a modal with resolved locals option does not work, logs "$q.resolve is not a function" in console

### ISSUE THREAD

**Issue by cammerman** [angular-ui/bootstrap#5490]
When attempting to open a modal with resolved members in the options, the modal does not appear, and an error is reported in the console saying "TypeError: $q.resolve is not a function"

Angular version: 1.4.0
angular-ui-bootstrap version: 1.1.1
I have reproduced the issue in this plunk: https://plnkr.co/edit/ZiAxQHNeXPCjYyTiWdhI

If you remove the "resolve" option from the .open call in the script file, the modal will work.

I believe the source of the problem is the $uibResolve service, which references a method $q.resolve, which does not exist on the Angular $q service. Unlike the OSS "q" async library, Angular has only the "when" function in its main API. As an emergency fix in our project I modified the ui-bootstrap source files to change the "resolve" to "when" and the modals now work for us.

**Comment by cammerman** [comment]
I looked at the Angular Github repo and see that as of Angular 1.5 released in November 2015 there is now a "resolve" alias on $q, but it did not exist prior to that.

**Comment by deeg** [comment]
This library is interfaced to work with angular 1.4.5 and later.

$q.resolve is a method in 1.4.5 so I suggest updating AngularJS

**Comment by wesleycho** [comment]
I should also add, ngAnimate is flawed prior to 1.4.5 - it's highly recommended to use 1.4.5+, if not 1.4.9, a highly stable release.

**Comment by wayjake** [comment]
Moving to 1.4.9 did the trick. Sadly I can't bump up to ~1.5 as that seems to be a pretty big change for some libraries, specifically ui-calendar. Thanks for the help!
